config/routes.rb
UnderBoutique::Application.routes.draw do

  root to: 'home#index'
  ActiveAdmin.routes(self)

  devise_for :admin_users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }, sign_out_via: [ActiveAdmin.application.logout_link_method]
  
  resources :admin_users, only:[:destroy]
  resources :cart_items, only: [:index, :create, :destroy]
  
  resource :order, only: [:new, :create]

  resources :designers, only: [:index, :show]

  resources :news, only: [:index] do
    collection do
      get "designer"
    end
  end

  resources :sale, only: [:index]

  resources :product, only: [:show, :index] do
    collection do
      get "ropa"
      get "zapatos"
      get "accesorios"
    end
  end

end

app/views/shared/_nav.html.haml
#header.container
  .navbar
    .logo
      = link_to '', root_path 
    %ul.nav
      %li#sale
        = link_to 'sale', sale_index_path
      %li#news
        = link_to 'novedades', news_index_path
      %li#designers
        = link_to 'diseñadores', designers_path
      %li#ropa
        %a(href='') ropa
      %li#shoes
        %a(href='') zapatos
      %li#accesories
        %a(href='') accesorios
      %li#gifts
        %a(href='') gifts
      %li#journal
        %a(href='') the journal
  .btn-group
    - if current_admin_user
      .btn
        = link_to('logout', destroy_admin_user_session_path, method: 'delete')
    - else
      .btn.login  
        %a Iniciar sesión
    .btn
      = link_to('Registrarse', new_admin_user_registration_path)
    .btn.search 
      %a Buscar
    .btn 
      = link_to 'cart', cart_items_path
  .search-box
    %form
      %input(type='text')
      %input(class='btn' type='submit' value='buscar')
  .login-box.span3
    = form_for(AdminUser.new, as: :admin_user, url: session_path(:admin_user)) do |f|
      = f.label :email
      = f.email_field :email
      = f.label :password
      = f.password_field :password
      = f.hidden_field :remember_me, value: 1
      .btns
        = f.submit 'iniciar sesión', class: 'btn'
        = link_to 'olvidó su contraseña', new_password_path(:admin_user), class: 'btn'

app/views/shared/_navigation.html.haml
#header
  .row-fluid
    .container
      .userbar
        %ul.pull-right
          %li
            = link_to('SignUp', 'admin_users/sign_up')
          %li
            %p ·
          - if current_admin_user
            %li
              = link_to('LogOut', destroy_admin_user_session_path, method: 'delete')
          - else
            %li
              = link_to('LogIn', 'admin_users/sign_in')
  .row-fluid
    .container  
      .navbar
        .navbar-inner
          = link_to "UNDERBOUTIQUE", {:controller => "home", :action => "index"}, :class => "brand" 
          %button.btn.btn-navbar.collapsed(type="button" data-toggle="collapse" data-target=".nav-collapse")+
          .nav-collapse.collapse.pull-right
            .row-fluid
              %ul.nav
                %li.news
                  = link_to('novedades', {:controller => "news", :action => "index"})
                %li.designers
                  = link_to('diseñadores',{:controller => "designers", :action => "index"} )
                %li#ropa
                  = link_to('ropa', {:controller => "product", :action => "index"})
                %li#shoes
                  = link_to('zapatos', {:controller => "product", :action => "index"})
                %li#accesories
                  = link_to('accesorios', {:controller => "product", :action => "index"})
                %li#sale
                  = link_to('sale', {:controller => "sale", :action => "index"})
                %li
                  = link_to 'cart', cart_items_path
            

app/views/shared/_product_link.html.haml
- if image = product.images.first
	= link_to(product_path(product.id)) do
		.ph{:style => "background-image: url(#{image.file.url(:large)})"} 
			.over
				.info
					%h1 #{product.name}
					%p $ #{product.price}
					.hr
					%h4.more ver mas