config/routes.rb
UnderBoutique::Application.routes.draw do

  root to: 'home#index'
  ActiveAdmin.routes(self)

  devise_for :admin_users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }, sign_out_via: [ActiveAdmin.application.logout_link_method]
  
  resources :admin_users, only:[:destroy]
  resources :cart_items, only: [:index, :create, :destroy]
  
  resource :order, only: [:new, :create]

  resources :designers, only: [:index, :show]

  resources :news, only: [:index] do
    collection do
      get "designer"
    end
  end

  resources :sale, only: [:index]

  resources :product, only: [:show, :index] do
    collection do
      get "ropa"
      get "zapatos"
      get "accesorios"
    end
  end

end

app/models/designer.rb
class Designer < ActiveRecord::Base
  has_many :images
  has_many :products
  has_many :collections
  has_many :orders
  validates :name, presence: true 
  attr_accessible :name, :bio, :images_attributes, :nombre, :direccion, :telefono, :cuit, :horario_entrega, :situacion_fiscal, as: [:admin, :default]
  attr_accessible :enabled, as: :admin
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  def index
    @designers = Designer.all
  end

  def show
    @designer = Designer.find(params[:id]) 
    @collections = Collection.find(:all, :conditions => {:designer_id => params[:id]})
  end
end

app/views/designers/index.html.haml
.container
  .row-fluid.collections
  - @designers.sort_by{|d| d.name}.group_by{|d| d.name[0].upcase}.each do |letter, members|
    .span4
      %h1= letter
      - members.each do |designer|
        .designer
          = link_to(designer.name, designer_path(designer.id), class: 'simple-btn')

app/views/designers/show.html.haml
.row-fluid
  .page#featured
    .slider--fullscreen
      .slider
        .slider-strip
          - @designer.images.each do |image|
            .slider-item{:style => "background-image: url(#{image.file.url(:large)})"} 
              .container
                .slider-info
                  %h1.checkcolor #{@designer.name}
        .slider-arrow.slider-arrow--left &#8249
        .slider-arrow.slider-arrow--right &#8250
        .slider-dots
.row-fluid
  .box.page#bio
    %h5 About
    .hr
    %p #{@designer.bio}    
.row-fluid
  .box.page#products
    .row-fluid
      %h5 Productos
    .row-fluid
      .hr
    .row-fluid
      %ul#filter
        %li.filter{ :data => { :filter => "cat1" }}
          %a.btn.info{ :href => "#" } Ropa 
        %li.filter{ :data => { :filter => "cat1" }}
          %a.btn.info{ :href => "#" } Zapatos 
        %li.filter{ :data => { :filter => "cat1" }}
          %a.btn.info{ :href => "#" } Accesorios 
.row-fluid.collections
  -(@designer.products.last(12)*6).each do |product|
    .span3{:class => "#{product.category}"}
      .item
        = render 'shared/product_link', product: product