config/routes.rb
UnderBoutique::Application.routes.draw do

  root to: 'home#index'
  ActiveAdmin.routes(self)

  devise_for :admin_users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions'
  }, sign_out_via: [ActiveAdmin.application.logout_link_method]
  
  resources :admin_users, only:[:destroy]
  resources :cart_items, only: [:index, :create, :destroy]
  
  resource :order, only: [:new, :create]

  resources :designers, only: [:index, :show]

  resources :news, only: [:index] do
    collection do
      get "designer"
    end
  end

  resources :sale, only: [:index]

  resources :product, only: [:show, :index] do
    collection do
      get "ropa"
      get "zapatos"
      get "accesorios"
    end
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def index
    @products = shopping_cart.items
    @designers = shopping_cart.items_by_designer
  end

  def create
    unless shopping_cart.add(params[:product_id], params[:quantity], params[:size])
      redirect_to({action: :index}, alert: 'No se pudo agregar el item al carrito porque ya no existe.')
      return
    end
    redirect_to action: :index
  end
  
  def destroy
    shopping_cart.delete(params[:id])
    redirect_to({action: :index}, alert: 'Sacamos el item de tu carrito.')
  end
end

app/views/cart_items/index.html.haml
.cart
  %h1 Tu carrito
  - @designers.each do |designer, products|
    %h2
      Items de #{designer.name}: Total $ #{shopping_cart.amount_for_designer(designer)}
    %ul
    .cart-items
      .row-fluid.items
        .span12
          - products.each do |item, quantity, size|
            .row-fluid
              .span12
                .cart-item
                  .span2
                    = image_tag(item.images.first.file.url(:small), class: 'ph')
                  .span5
                    %h4 #{item.name}
                    %p #{item.description}
                  .span1
                    %label talle 
                    %br
                    %p #{size}
                  .span1
                    %label cantidad 
                    %input(type="number" class="quantity" name="quantity" style="width:50px; margin-top:10px;" value="#{quantity}" min="1" max="1000")
                  .span1
                    %label precio
                    %br
                    %p.precio $#{item.price*quantity}
                    = hidden_field_tag 'item_price', item.price 
                  .span1
                    = link_to('Quitar', cart_item_path("#{item.id}_#{size}"), method: 'delete', :class => "delete")
  
  %br
  .row-fluid
    .span12
      = link_to 'Seguir comprando', root_path, :class => "nav seguir"
      = link_to 'Checkout', new_order_path, :class => "nav"